GET http://127.0.0.1:8000/api/app/
Authorization: Basic sm sm

###

GET http://127.0.0.1:8000/api/app/1/
Authorization: Basic sm sm

###

PUT http://127.0.0.1:8000/api/app/1/
Authorization: Basic sm sm

{
"name": "new name",
"key": "123123123",
"custom_data": "asdasd"
}

###

POST http://127.0.0.1:8000/api/app/1/refresh/
Authorization: Basic sm sm

###

GET http://127.0.0.1:8000/api/test/

###

GET http://127.0.0.1:8000/api/test/
Authorization: Token 244c65fd9e801a4892cf2d20562be476600545e4

###

GET http://127.0.0.1:8000/api/test/
Authorization: Token 896d671be868020fa6526cdfa3886fe06d485738

###
